### ISSUE TITLE
Comment: SSL avoison best to maximize earnings

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/adblock-notify-by-bweb#14]
Your plugin description suggests this code will work with SSL + only novices will make the mistake of using HTTPS/SSL wrapped content, as this can reducing earnings by 75%+.

This is because HTTPS sites can only inject HTTPS sourced Ads. When an Ad Network, like Adsense or any other, senses HTTPS the target site of an Ad Unit must be HTTPS, then all non-HTTPS Ads are pruned from the Ad Pool, which currently is 75%+ of all Ads.

So, even though your code may work with SSL...

Sites monetizing with Ad Networks, best only be running non-SSL.

And, the trick here is to wrap admin + protected pages with HTTPS + force all other pages to HTTP. This blocks hackers from sniffing user/pass combos + forces content to work with 100% of Ad Networks.

You might make mention of this in your Description, lest unsuspecting novices wrap their sites in SSL + wonder why their earnings are so low.

Source: https://wordpress.org/support/topic/comment-ssl-avoison-best-to-maximize-earnings?replies=1#post-8412854

@selu91

**Comment by selul** [comment]
@ineagu @HardeepAsrani  do you have any understanding of this ? maybe i'm missing smth

**Comment by ineagu** [comment]
in simpler words, the guy recommend to use ssl just for wp-admin part and not for site views :)
