### ISSUE TITLE
update fuckadblock

### ISSUE THREAD

**Issue by selul** [Codeinwp/adblock-notify-by-bweb#17]
@contactashish13 can you update the fuckadblock script to the latest version, it's found on an-detect.min.js

**Comment by selul** [comment]
and the site is https://fuckadblock.sitexw.fr/ 

make sure all the things are working properly after.

**Comment by contactashish13** [comment]
sdf

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/adblock-notify-by-bweb/pull/18

**Comment by selul** [comment]
@contactashish13 please remove this change and close the PR, i checked the code and fuckadblock was no longer used. 

sorry for confussion

**Comment by selul** [comment]
@contactashish13 please close the issue when you are done
