### ISSUE TITLE
Create PRO repo and discuss all suggestions

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/adblock-notify-by-bweb#2]
ADBLOCK : http://fuckadblock.sitexw.fr/ 
ADBLOCK : Add an option to show credits to the plugin
ADBLOCK PRO : ajouter option pour choisir le chemin (pro)
ADBLOCK PRO : preview mode
ADBLOCK PRO : show the lightbox on specific pages
ADBLOCK PRO : add a way to show different messages based on the visitor language
ADBLOCK PRO : add multiple modal default styles
ADBLOCK PRO : Multisite support
ADBLOCK PRO : Show the modal after x pages viewed

**Comment by rodica-andronache** [comment]
@ineagu how will the pro plugin be called? Adblock Notify Pro or just Adblock Pro ?

**Comment by ineagu** [comment]
Adblock Notify Pro

On Wed, Apr 20, 2016 at 2:07 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> Assigned #2 <https://github.com/Codeinwp/adblock-notify-by-bweb/issues/2>
> to @ineagu <https://github.com/ineagu>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/adblock-notify-by-bweb/issues/2#event-634435146>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
https://github.com/Codeinwp/adblock-notify-pro
