### ISSUE TITLE
Modal renders at bottom of page

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/adblock-notify-by-bweb#21]
@selul the modal seems to render at the bottom of the page, 2 reports of this so far and it does the same on my local install.

http://prntscr.com/cnwtei

**Comment by selul** [comment]
@UVLabs can you tell me which theme are you using ?

**Comment by lionelleboiteux** [comment]
Hi,

I use Newspaper (https://themeforest.net/item/newspaper/5489609) v7.4

**Comment by UVLabs** [comment]
@selul it happened on on some of our themes sadly i didnt take down which. @lionelleboiteux could you please provide us with a link to your website?

**Comment by lionelleboiteux** [comment]
My site is

http://fantasy-coach.fr/

But the person who raised the bug got the same problem on his local vanilla
environment.

**Comment by UVLabs** [comment]
@selul

**Comment by selul** [comment]
@contactashish13 can you check

**Comment by contactashish13** [comment]
@UVLabs @lionelleboiteux can you click the checkbox next to "Will recreate the selectors and temps files on options saved." and then try again?

![image](https://cloud.githubusercontent.com/assets/12953439/19279955/34dfc9bc-9001-11e6-8bdf-0f825b8b2276.png)

**Comment by lionelleboiteux** [comment]
This indeed solves the issue. Thanks for your help.
