### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/adblock-notify-by-bweb#23]
Is plugin compatible? @selul https://wordpress.org/support/topic/php-7-support-14/

I don't currently use PHP 7 @Basilakis

**Comment by selul** [comment]
@contactashish13 can you check please ?

**Comment by contactashish13** [comment]
@selul the plugin WP Engine compatibility checker hangs on my dev environment as well as qsandbox so I'm unable to test. Nevertheless, my dev environment is php 7.0.8 and the ad block plugin works well.

**Comment by selul** [comment]
closing as invalid
