### ISSUE TITLE
New banner and icon images for wordpress.org

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/adblock-notify-by-bweb#3]

**Comment by abaicus** [comment]
![banner_adblock](https://cloud.githubusercontent.com/assets/15010186/14779611/91a0414a-0ae1-11e6-9e2e-a2c59178a9ee.png)
![icon_adblock](https://cloud.githubusercontent.com/assets/15010186/14779613/91b996c2-0ae1-11e6-8a52-44491efe6f2d.png)
