### ISSUE TITLE
[WP4.7] Not compatible

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/adblock-notify-by-bweb#36]
So far I've noticed that Freemius doesn't work during activation and deactivation:

![image](https://cloud.githubusercontent.com/assets/10324144/20553470/498f243e-b12b-11e6-9187-4f8b9f107d59.png)

@selul

**Comment by selul** [comment]
i think you have the adblock chrome plugin active, is not related to wp 4.7

**Comment by UVLabs** [comment]
@selul yeah so i guess aside from that it's compatible. Do we have some way of fixing this? If not just close ticket.

I also can't deactivate the plugin if Adblock is enabled lol

**Comment by selul** [comment]
yes, that's right, we can not fix it as adblock is blocking any script coming from our plugin
