### ISSUE TITLE
add pages to exclude for checking 

### ISSUE THREAD

**Issue by selul** [Codeinwp/adblock-notify-by-bweb#42]
add the feature, in the advanced tab, to exclude pages ( post_type=page )  where the popup/redirect message should show up. 

this would be a pro version only feature but the control will be displayed in the disabled state in the lite version. 

The control will be  multiselect and users can choose multiple pages to show up. 

Also you need to not gather stats for those pages, so please test if the page is excluded we dont fire that `call_an_adblock_counter` ajax call 

The way i would recommend you to do it is to check if the current page is excluded in the `an_enqueue_an_sripts` function and return if it is.

**Comment by ineagu** [comment]
I believe that we can also disable on certain post types, for example on themeisle, we can disable on downloads CPT and associated taxonomies. or woocommerce products + categories.

**Comment by selul** [comment]
@contactashish13 let's add something similar with advanced custom fields : 

http://prntscr.com/e038qo 

![image](https://cloud.githubusercontent.com/assets/3330746/22287427/8fda91a6-e2fb-11e6-969c-b006739c06f1.png)

I would like to have a similar selector, but remove irelevant options like logged in, attachment user. 

The filter will allow multiple conditions grouped by or/and clauses, like acf is doing.

**Comment by contactashish13** [comment]
@selul PRs: https://github.com/Codeinwp/adblock-notify-by-bweb/pull/46 and https://github.com/Codeinwp/adblock-notify-pro/pull/14

I've added only 3 fields now: post type, post status and category. Let me know if you want more to be added.
