### ISSUE TITLE
add redirect when disabled

### ISSUE THREAD

**Issue by selul** [Codeinwp/adblock-notify-by-bweb#43]
@contactashish13 when using the redirect option, users with adblock get redirected on a specific page. 

I would like after they get the adblock disabled, if they refresh to return to the page that they previously wanted to see. 

try to use localStorage to store the page that they want to see and a flag with the current adblock status. if the status is changing redirect to the localStorage page.  also make sure you check the status and update it  before updating the current page.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/adblock-notify-by-bweb/pull/45
