### ISSUE TITLE
check redirect option

### ISSUE THREAD

**Issue by selul** [Codeinwp/adblock-notify-by-bweb#44]
@contactashish13 users are complaining that when redirect is active and they have disabled Adblock, the redirect is still happening. 

Here is a message: 

> My website has thousands of access everyday, i've been recieving a lot of complainings from my visitors that even when they deactivate adblock for my website, the plugin keeps on redirecting them. I use the redirect function, to redirect on every pageview. They've sent me printscreens and they really have my website on the "white list" and the plugin keeps on redirecting them

Can you have a look please and try the scenario ?

**Comment by contactashish13** [comment]
@selul I believe the problem could be in people misunderstanding how to whitelist the site.

Once they click "dont run on this domain", the below pop up appears. They need to click exclude. If they dont, and close/cancel the popup, ad block continues to run on the domain.
![image](https://cloud.githubusercontent.com/assets/12953439/22365218/4f1db07e-e49c-11e6-9e3b-c84ccf83e195.png)

is it possible to get an example screenshot of how users have whitelisted the site?
