### ISSUE TITLE
Themeisle page text

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/adblock-notify-by-bweb#5]
seo-friendly titles/description

We need to talk to @mariusghitulescu for this

**Comment by abaicus** [comment]
De la Adelina: 

> AdBlock Notify
> 
> Ads keep your business alive. Detect users who use AdBlock and send them notifications
> 
> A passive approach to make people disable ad blockers
> Increase your ad revenue by finding out who is using AdBlock and let them know how important this is to you.
> 
> 
> Features
> 
> - Blocks the ad blockers
> It was made to detect the tools that are meant to stop the ads from showing up on websites. By the way, the plugin won't be blocked by AdBlock because it comes equipped with random selectors and files which prevent this from happening.
> 
> - Custom notification messages 
> After discovering who is using AdBlock, you can send them notification messages, which you can easily customize through jQuery Popup or Javascript redirect.
> 
> - Mobile ready
> The plugin works on mobile phones the same way it does on desktops and tablets. AdBlock will be detected no matter what device you're using.
> 
> - Design options and custom CSS
> Apart from creating custom notification messages, the way they show up to your users matters. You can choose from various visual options for the popup: effects, animations, colors, title etc. Besides, you can write custom CSS to make it even more interesting.
> 
> - Counter and statistics
> Get stats and numbers about your ads right from your WordPress dashboard. Find out how many users are using ad blockers, how many disabled them at your request, your ads' visibility etc.


@mariusghitulescu Daca poti arunca un ochi peste ce e aici si sa te uiti putin cat de SEO friendly este.
